const sidebars: SidebarsConfig = {
  frontdoorSidebar: [
    {
      type: 'html',
      value: '<div class="sidebar-product-header">Frontdoor Docs</div>', // Set your header text here
      defaultStyle: false,
    },
    { type: 'autogenerated', dirName: 'frontdoor' },
  ],
  openzitiSidebar: [
    {
      type: 'html',
      value: '<div class="sidebar-product-header">OpenZiti Docs</div>', // Different text for different product
      defaultStyle: false,
    },
    { type: 'autogenerated', dirName: 'openziti' },
  ],
};