FROM node:20-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
      doxygen wget curl jq git openssh-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
