name: build-docs-container

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-container.yml'
      - 'Dockerfile.docs-ci'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.docs-ci
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docs-ci:latest

