name: mattermost-build-notify
on:
  workflow_run:
    workflows: ["build and deploy docs"]
    types: [completed]

jobs:
  mattermost-build-notify:
    if: |
      github.repository_owner == 'netfoundry'
      && (github.event.workflow_run.conclusion == 'success'
      || github.event.workflow_run.conclusion == 'failure')
    runs-on: ubuntu-latest
    name: POST build result to doc-alerts
    steps:
      - uses: openziti/ziti-mattermost-action-py@v1
        with:
          zitiId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
          webhookUrl: ${{ secrets.ZHOOK_URL_DOC_NOTIFICATIONS }}
          eventJson: ${{ toJson(github.event) }}
          senderUsername: "GitHubZ"
