name: Trigger Doc Publish

on:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: main
      inputs:
        required: false
        type: string
        default: "{}"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout script
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/trigger-docs.sh
          path: docusaurus-shared

      - name: Run trigger-docs.sh
        working-directory: docusaurus-shared/scripts
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
          GH_WORKFLOW: ${{ inputs.workflow }}
          GH_REF: ${{ inputs.ref }}
          GH_INPUTS: ${{ inputs.inputs }}
          GH_REPO_OWNER: ${{ github.repository_owner }}
          GH_REPO_NAME: ${{ github.event.repository.name }}
        run: ./trigger-docs.sh
