name: Trigger Doc Publish

on:
  workflow_call:
    inputs:
      workflow:
        type: string
        default: publish.yml
      ref:
        required: false
        type: string
        default: main
      inputs:
        required: false
        type: string
        default: "{}"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trigger-docs.sh
        uses: actions/checkout@v4
        with:
          repository: netfoundry/docusaurus-shared
          sparse-checkout: unified-doc/scripts/trigger-docs.sh
          sparse-checkout-cone-mode: false
          path: docusaurus-shared

      - name: Run trigger-docs.sh
        run: ./docusaurus-shared/unified-doc/scripts/trigger-docs.sh
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
          GH_WORKFLOW: ${{ inputs.workflow }}
          GH_REF: ${{ inputs.ref }}
          GH_INPUTS: ${{ inputs.inputs }}
          GH_REPO_OWNER: "netfoundry"
          GH_REPO_NAME: "docusaurus-shared"
